const now = new Date();
const daysAgo = (d) => new Date(now.getTime() - d * 24 * 60 * 60 * 1000);

const videos = [
  {
    title: 'HIGHLIGHTS: Burnley 0-0 AFC Bournemouth',
    category: 'highlights',
    thumbnail: 'https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?w=600',
    videoUrl: '',
    duration: '5:14',
    premium: true,
    publishedAt: daysAgo(1),
    description: 'Watch the highlights from Burnley\'s goalless draw with AFC Bournemouth at Turf Moor.',
  },
  {
    title: 'HIGHLIGHTS: Leeds United 2-1 Burnley',
    category: 'highlights',
    thumbnail: 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=600',
    videoUrl: '',
    duration: '6:32',
    premium: true,
    publishedAt: daysAgo(4),
    description: 'Extended highlights from Burnley\'s defeat at Elland Road.',
  },
  {
    title: 'PARKER: Post-Match Reaction vs Bournemouth',
    category: 'interviews',
    thumbnail: 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?w=600',
    videoUrl: '',
    duration: '3:42',
    premium: true,
    publishedAt: daysAgo(1),
    description: 'Head Manager Scott Parker speaks to the media after the draw with Bournemouth.',
  },
  {
    title: 'FOSTER: "We Have The Quality To Win"',
    category: 'interviews',
    thumbnail: 'https://images.unsplash.com/photo-1463453091185-61582044d556?w=600',
    videoUrl: '',
    duration: '2:58',
    premium: true,
    publishedAt: daysAgo(2),
    description: 'Striker Lyle Foster on the team\'s ambitions for the rest of the season.',
  },
  {
    title: 'TRAINING: Clarets Prepare for Norwich',
    category: 'training',
    thumbnail: 'https://images.unsplash.com/photo-1486286701208-1d58e9338013?w=600',
    videoUrl: '',
    duration: '4:07',
    premium: true,
    publishedAt: daysAgo(3),
    description: 'Behind the scenes at Barnfield as the squad prepares for the weekend fixture.',
  },
  {
    title: 'TRAINING: Set-Piece Work Ahead of Norwich',
    category: 'training',
    thumbnail: 'https://images.unsplash.com/photo-1522778119026-d647f0596c20?w=600',
    videoUrl: '',
    duration: '3:21',
    premium: false,
    publishedAt: daysAgo(4),
    description: 'Free training footage — the coaching staff work on set-pieces.',
  },
  {
    title: 'WOMEN: Match Highlights vs Wolverhampton',
    category: 'academy-women',
    thumbnail: 'https://images.unsplash.com/photo-1560272564-c83b66b1ad12?w=600',
    videoUrl: '',
    duration: '6:22',
    premium: false,
    publishedAt: daysAgo(2),
    description: 'Watch all the action from Burnley Women\'s 1-0 win over Wolverhampton Wanderers.',
  },
  {
    title: 'ACADEMY: Under-18 Highlights vs Blackburn',
    category: 'academy-women',
    thumbnail: 'https://images.unsplash.com/photo-1547940575-1b2b5e34f33f?w=600',
    videoUrl: '',
    duration: '4:55',
    premium: false,
    publishedAt: daysAgo(5),
    description: 'The Under-18s secured a 2-1 win over local rivals Blackburn Rovers.',
  },
];

module.exports = videos;
