const articles = [
  {
    title: "MATCH REPORT: LIKHU BHUJEE RYC 0 - 0 BIGU",
    slug: "match-report-likhu-bhujee-0-0-bigu",
    category: "match-reports",
    summary: "Likhu Bhujee RYC and Bigu played out a goalless draw at Amrit Gamchaya in a hard-fought Bhujee League clash.",
    body: "<p>Likhu Bhujee RYC and Bigu shared the spoils in a tight 0-0 draw at Amrit Gamchaya. Abiraj Sunuwar's side were resolute defensively and created several chances but couldn't find a breakthrough.</p>",
    imageUrl: "https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=800",
    readTime: 3, team: "men", featured: true,
    publishedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
  },
  {
    title: "MATCH PREVIEW: LIKHU BHUJEE RYC V ABC ",
    slug: "match-preview-likhu-bhujee-ryc-v-abc",
    category: "match-previews",
    summary: "Likhu Bhujee RYC travel to the manthali to face ABC in the final game of the season.",
    body: "<p>Likhu Bhujee RYC make the trip to manthali to face ABC on Monday evening. Abiraj's side look to end the season on a high.</p>",
    imageUrl: "https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?w=800",
    readTime: 3, team: "men", featured: true,
    publishedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
  },
  {
    title: "Abiraj's POST-MATCH POINTS: BIGU",
    slug: "abirajs-post-match-points-bigu",
    category: "club-news",
    summary: "Manager Abiraj Sunuwar shares his thoughts following Tuesday's goalless draw.",
    body: "<p>Abiraj Sunuwar reflected on a solid defensive performance and expressed pride in his squad's efforts after the draw with Bigu.</p>",
    imageUrl: "https://images.unsplash.com/photo-1508098682722-e99c43a406b2?w=800",
    readTime: 2, team: "men", featured: false,
    publishedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
  },
  {
    title: "WOMEN'S MATCH REPORT: LIKHU BHUJEE RYC 1-0 WE ARE BROTHERS WOMEN",
    slug: "womens-match-report-likhu-bhujee-ryc-1-0-we-are-brothers-women",
    category: "match-reports",
    summary: "Likhu Bhujee RYC secured a vital three points with a narrow 1-0 win over We Are Brothers Women.",
    body: "<p>Likhu Bhujee RYC continued their impressive form with a hard-fought 1-0 victory over We Are Brothers Women at Amrit Gamchaya.</p>",
    imageUrl: "https://images.unsplash.com/photo-1560272564-c83b66b1ad12?w=800",
    readTime: 3, team: "women", featured: false,
    publishedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
  },
  {
    title: "GALLERY: TRAINING AHEAD OF BHAMTI BHANDAR",
    slug: "gallery-training-ahead-of-bhamti-bhandar",
    category: "training",
    summary: "Take a look at the best shots from training as the squad prepared for Tuesday's clash.",
    body: "<p>The libhuras trained at NSF ground ahead of the Bhamti Bhandar match. Here are the best photos from the session.</p>",
    imageUrl: "https://images.unsplash.com/photo-1486286701208-1d58e9338013?w=800",
    readTime: 1, team: "men", featured: false,
    publishedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
  },
  {
    title: "WHAT'S ON THIS WEEK: A GUIDE TO THE WEEK AHEAD",
    slug: "whats-on-this-week-guide",
    category: "club-news",
    summary: "Everything you need to know about the week ahead at Likhu Bhujee Ramechhap Youth Club.",
    body: "<p>From first-team action to community events, here's a guide to everything happening at the club this week.</p>",
    imageUrl: "https://images.unsplash.com/photo-1522778119026-d647f0596c20?w=800",
    readTime: 3, team: "general", featured: false,
    publishedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
  },
  {
    title: "SEASON TICKETS 2025/26: ON SALE NOW",
    slug: "season-tickets-2025-26-on-sale",
    category: "ticket-news",
    summary: "Season tickets for the 2025/26 campaign are now available to purchase.",
    body: "<p>Likhu Bhujee Ramechhap Youth Club is pleased to announce that season tickets for the 2025/26 season are now on sale. Secure your seat at Amrit Gamchaya today.</p>",
    imageUrl: "https://images.unsplash.com/photo-1547940575-1b2b5e34f33f?w=800",
    readTime: 2, team: "general", featured: true,
    publishedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
  },
  {
    title: "COMMUNITY: LIBHURAS IN THE COMMUNITY SUMMER PROGRAMME",
    slug: "community-libhuras-summer-programme",
    category: "community",
    summary: "Libhuras in the Community launches its summer programme for young fans across Ramechhap.",
    body: "<p>Libhuras in the Community is delighted to launch its summer programme, offering activities for young people across the borough.</p>",
    imageUrl: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=800",
    readTime: 2, team: "general", featured: false,
    publishedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
  },
];

module.exports = articles;
