const players = [
  // ── GOALKEEPERS ────────────────────────────────────────────────
  {
    name: 'Prabat Rai', slug: 'prabat-rai',
    position: 'goalkeeper', squad: 'men', shirtNumber: 1,
    nationality: 'Nepal', height: '5\'6"',
    photoAsset: { secureUrl: 'https://images.unsplash.com/photo-1624526267942-ab0ff8a3e972?w=400&h=533&fit=crop&crop=face', resourceType: 'image' },
    bio: 'Prabat Rai is a highly rated Nepal international goalkeeper who joined LikhuBhujee Ramechhap. Known for his commanding presence and shot-stopping ability.',
    stats: { appearances: 38, goals: 0, assists: 0, cleanSheets: 12, yellowCards: 1, redCards: 0 },
  },
  {
    name: 'Yubin Tamanag', slug: 'yubin-tamanag',
    position: 'goalkeeper', squad: 'men', shirtNumber: 13,
    nationality: 'Nepal', height: '5\'9"',
    photoAsset: { secureUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&h=533&fit=crop&crop=face', resourceType: 'image' },
    bio: 'Experienced Nepal goalkeeper providing competition and cover for the number one shirt at LikhuBhujee Ramechhap.',
    stats: { appearances: 10, goals: 0, assists: 0, cleanSheets: 3, yellowCards: 0, redCards: 0 },
  },

  // ── DEFENDERS ──────────────────────────────────────────────────
  {
    name: 'Ashim Mahat', slug: 'ashim-mahat',
    position: 'defender', squad: 'men', shirtNumber: 2,
    nationality: 'Nepal', height: '5\'7"',
    photoAsset: { secureUrl: 'https://images.unsplash.com/photo-1564564321837-a57b7070ac4f?w=400&h=533&fit=crop&crop=face', resourceType: 'image' },
    bio: 'Nepal international right-back known for his energy and athleticism. Ashim Mahat is a key part of the LikhuBhujee Ramechhap backline.',
    stats: { appearances: 34, goals: 1, assists: 5, cleanSheets: 0, yellowCards: 4, redCards: 0 },
  },
  {
    name: 'Mandish Bhujel', slug: 'mandish-bhujel',
    position: 'defender', squad: 'men', shirtNumber: 3,
    nationality: 'Nepal', height: '5\'6"',
    photoAsset: { secureUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&h=533&fit=crop&crop=face', resourceType: 'image' },
    bio: 'Young left-back on loan who has impressed with his composure and defensive solidity.',
    stats: { appearances: 24, goals: 0, assists: 2, cleanSheets: 0, yellowCards: 2, redCards: 0 },
    onLoan: true,
  },
  {
    name: 'Shailesh Mahatara', slug: 'shailesh-mahatara',
    position: 'defender', squad: 'men', shirtNumber: 5,
    nationality: 'Nepal', height: '6\'1"',
    photoAsset: { secureUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=533&fit=crop&crop=face', resourceType: 'image' },
    bio: 'Nepal centre-back who brings technical quality and calmness in possession.',
    stats: { appearances: 28, goals: 0, assists: 1, cleanSheets: 0, yellowCards: 3, redCards: 0 },
  },
  {
    name: 'Wangja Gurung', slug: 'wangja-gurung',
    position: 'defender', squad: 'men', shirtNumber: 6,
    nationality: 'Nepal', height: '5\'8"',
    photoAsset: { secureUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=533&fit=crop&crop=face', resourceType: 'image' },
    bio: 'Nepal centre-back who joined from We Are Brothers. Commanding in the air and strong in the tackle.',
    stats: { appearances: 32, goals: 2, assists: 0, cleanSheets: 0, yellowCards: 5, redCards: 1 },
  },
  {
    name: 'Suman Tailor', slug: 'suman-tailor',
    position: 'defender', squad: 'men', shirtNumber: 33,
    nationality: 'Nepal', height: '5\'8"',
    photoAsset: { secureUrl: 'https://images.unsplash.com/photo-1544723795-3fb6469f5b39?w=400&h=533&fit=crop&crop=face', resourceType: 'image' },
    bio: 'Nepali left-back known for his attacking instincts and technical quality on the ball.',
    stats: { appearances: 20, goals: 0, assists: 3, cleanSheets: 0, yellowCards: 2, redCards: 0 },
  },
  {
    name: 'Madan Bhujel', slug: 'madan-bhujel',
    position: 'defender', squad: 'men', shirtNumber: 35,
    nationality: 'Nepal', height: '5\'6"',
    photoAsset: { secureUrl: 'https://images.unsplash.com/photo-1463453091185-61582044d556?w=400&h=533&fit=crop&crop=face', resourceType: 'image' },
    bio: 'Nepali defender who has come through the LBRYC academy system and earned his first-team opportunities.',
    stats: { appearances: 10, goals: 0, assists: 1, cleanSheets: 0, yellowCards: 1, redCards: 0 },
  },

  // ── MIDFIELDERS ────────────────────────────────────────────────
  {
    name: 'Chandra Hang', slug: 'chandra-hang',
    position: 'midfielder', squad: 'men', shirtNumber: 6,
    nationality: 'Nepal', height: '5\'6"',
    photoAsset: { secureUrl: 'https://images.unsplash.com/photo-1547425260-76bcadfb4f2c?w=400&h=533&fit=crop&crop=face', resourceType: 'image' },
    bio: 'Nepali midfielder. A combative and technically proficient player who acts as the engine room in Abiraj\'s midfield.',
    stats: { appearances: 38, goals: 7, assists: 4, cleanSheets: 0, yellowCards: 7, redCards: 0 },
  },
  {
    name: 'Nurbu Sherpa', slug: 'nurbu-sherpa',
    position: 'midfielder', squad: 'men', shirtNumber: 7,
    nationality: 'Nepal', height: '5\'5"',
    photoAsset: { secureUrl: 'https://images.unsplash.com/photo-1552058544-f2b08422138a?w=400&h=533&fit=crop&crop=face', resourceType: 'image' },
    bio: 'Creative midfielder and set-piece specialist. Nurbu Sherpa joined on loan and has been instrumental in Lbryc\'s attacking play.',
    stats: { appearances: 22, goals: 6, assists: 9, cleanSheets: 0, yellowCards: 3, redCards: 0 },
    onLoan: true,
  },
  {
    name: 'Prabin Rai', slug: 'prabin-rai',
    position: 'midfielder', squad: 'men', shirtNumber: 8,
    nationality: 'Nepal', height: '5\'6"',
    photoAsset: { secureUrl: 'https://images.unsplash.com/photo-1531427186611-ecfd6d936c79?w=400&h=533&fit=crop&crop=face', resourceType: 'image' },
    bio: 'Talented Nepali midfielder on loan from Priti. Energetic box-to-box player with an eye for goal.',
    stats: { appearances: 30, goals: 4, assists: 5, cleanSheets: 0, yellowCards: 6, redCards: 0 },
    onLoan: true,
  },
  {
    name: 'Nima Sherpa', slug: 'nima-sherpa',
    position: 'midfielder', squad: 'men', shirtNumber: 10,
    nationality: 'Nepal', height: '5\'7"',
    photoAsset: { secureUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400&h=533&fit=crop&crop=face', resourceType: 'image' },
    bio: 'Nepali attacking midfielder who possesses excellent technical ability and contributes regularly with goals and assists.',
    stats: { appearances: 28, goals: 9, assists: 5, cleanSheets: 0, yellowCards: 4, redCards: 0 },
  },
  {
    name: 'Saroj Sunuwar', slug: 'saroj-sunuwar',
    position: 'midfielder', squad: 'men', shirtNumber: 16,
    nationality: 'Nepal', height: '5\'5"',
    photoAsset: { secureUrl: 'https://images.unsplash.com/photo-1566492031773-4f4e44671857?w=400&h=533&fit=crop&crop=face', resourceType: 'image' },
    bio: 'Nepali midfielder who brings physicality and composure to the midfield.',
    stats: { appearances: 16, goals: 0, assists: 2, cleanSheets: 0, yellowCards: 2, redCards: 0 },
    onLoan: true,
  },

  // ── FORWARDS ───────────────────────────────────────────────────
  {
    name: 'Rabin Thapa', slug: 'rabin-thapa',
    position: 'forward', squad: 'men', shirtNumber: 9,
    nationality: 'Nepal', height: '5\'5"',
    photoAsset: { secureUrl: 'https://images.unsplash.com/photo-1463453091185-61582044d556?w=400&h=533&fit=crop&crop=face', resourceType: 'image' },
    bio: 'Nepali striker who is one of Lbryc\'s most potent attacking threats.',
    stats: { appearances: 32, goals: 14, assists: 4, cleanSheets: 0, yellowCards: 2, redCards: 0 },
  },
  {
    name: 'Micheal Magar', slug: 'micheal-magar',
    position: 'forward', squad: 'men', shirtNumber: 11,
    nationality: 'Nepal', height: '5\'8"',
    photoAsset: { secureUrl: 'https://images.unsplash.com/photo-1459499362902-55a20553e082?w=400&h=533&fit=crop&crop=face', resourceType: 'image' },
    bio: 'Nepali international forward with explosive pace and a sharp finishing instinct. Has been one of the standout players in the squad this season.',
    stats: { appearances: 30, goals: 20, assists: 3, cleanSheets: 0, yellowCards: 3, redCards: 0 },
  },
  {
    name: 'Prakash Basnet', slug: 'prakash-basnet',
    position: 'forward', squad: 'men', shirtNumber: 17,
    nationality: 'Nepal', height: '5\'10"',
    photoAsset: { secureUrl: 'https://images.unsplash.com/photo-1617979420888-3ee7b5c91ef0?w=400&h=533&fit=crop&crop=face', resourceType: 'image' },
    bio: 'Nepali winger who terrorises opposition defences with his directness and trickery. A key creative outlet for the Libhuras.',
    stats: { appearances: 26, goals: 15, assists: 7, cleanSheets: 0, yellowCards: 1, redCards: 0 },
  },

  // ── COACHING STAFF ─────────────────────────────────────────────
  {
    name: 'Abiraj Sunuwar', slug: 'abiraj-sunuwar',
    position: 'coaching-staff', squad: 'men', shirtNumber: null,
    nationality: 'Nepal',
    photoAsset: { secureUrl: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=400&h=533&fit=crop&crop=face', resourceType: 'image' },
    bio: 'Abiraj Sunuwar is the current Head Manager of LikhuBhujee Ramechhap. He brings significant experience and a clear tactical identity to the club.',
    stats: { appearances: 0, goals: 0, assists: 0, cleanSheets: 0, yellowCards: 0, redCards: 0 },
  },
  {
    name: 'Khiroj Sunuwar', slug: 'khiroj-sunuwar',
    position: 'coaching-staff', squad: 'men', shirtNumber: null,
    nationality: 'Nepal',
    photoAsset: { secureUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=533&fit=crop&crop=face', resourceType: 'image' },
    bio: 'Nepali coach with extensive experience in developing young talent. Brings a wealth of knowledge and a player-centric approach to the team.',
    stats: { appearances: 0, goals: 0, assists: 0, cleanSheets: 0, yellowCards: 0, redCards: 0 },
  },
];

module.exports = players;
