const articles = [
  {
    title: "MATCH REPORT: BURNLEY 0 - 0 AFC BOURNEMOUTH",
    slug: "match-report-burnley-0-0-afc-bournemouth",
    category: "match-reports",
    summary: "Burnley and AFC Bournemouth played out a goalless draw at Turf Moor in a hard-fought Championship clash.",
    body: "<p>Burnley and AFC Bournemouth shared the spoils in a tight 0-0 draw at Turf Moor. Scott Parker's side were resolute defensively and created several chances but couldn't find a breakthrough.</p>",
    imageUrl: "https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=800",
    readTime: 3, team: "men", featured: true,
    publishedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
  },
  {
    title: "MATCH PREVIEW: BURNLEY V ARSENAL",
    slug: "match-preview-burnley-v-arsenal",
    category: "match-previews",
    summary: "Burnley travel to the Emirates to face Arsenal in the final game of the season.",
    body: "<p>Burnley make the trip to north London to face Arsenal on Monday evening. Parker's Clarets look to end the season on a high.</p>",
    imageUrl: "https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?w=800",
    readTime: 3, team: "men", featured: true,
    publishedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
  },
  {
    title: "PARKER'S POST-MATCH POINTS: AFC BOURNEMOUTH",
    slug: "parkers-post-match-points-afc-bournemouth",
    category: "club-news",
    summary: "Manager Scott Parker shares his thoughts following Tuesday's goalless draw.",
    body: "<p>Scott Parker reflected on a solid defensive performance and expressed pride in his squad's efforts after the draw with AFC Bournemouth.</p>",
    imageUrl: "https://images.unsplash.com/photo-1508098682722-e99c43a406b2?w=800",
    readTime: 2, team: "men", featured: false,
    publishedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
  },
  {
    title: "WOMEN'S MATCH REPORT: BURNLEY 1-0 WOLVERHAMPTON WANDERERS",
    slug: "womens-match-report-burnley-1-0-wolves",
    category: "match-reports",
    summary: "Burnley Women secured a vital three points with a narrow 1-0 win over Wolves.",
    body: "<p>Burnley Women continued their impressive form with a hard-fought 1-0 victory over Wolverhampton Wanderers at Turf Moor.</p>",
    imageUrl: "https://images.unsplash.com/photo-1560272564-c83b66b1ad12?w=800",
    readTime: 3, team: "women", featured: false,
    publishedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
  },
  {
    title: "GALLERY: TRAINING AHEAD OF AFC BOURNEMOUTH",
    slug: "gallery-training-ahead-of-afc-bournemouth",
    category: "training",
    summary: "Take a look at the best shots from training as the squad prepared for Tuesday's clash.",
    body: "<p>The Clarets trained at Barnfield ahead of the Bournemouth match. Here are the best photos from the session.</p>",
    imageUrl: "https://images.unsplash.com/photo-1486286701208-1d58e9338013?w=800",
    readTime: 1, team: "men", featured: false,
    publishedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
  },
  {
    title: "WHAT'S ON THIS WEEK: A GUIDE TO THE WEEK AHEAD",
    slug: "whats-on-this-week-guide",
    category: "club-news",
    summary: "Everything you need to know about the week ahead at Burnley Football Club.",
    body: "<p>From first-team action to community events, here's a guide to everything happening at the club this week.</p>",
    imageUrl: "https://images.unsplash.com/photo-1522778119026-d647f0596c20?w=800",
    readTime: 3, team: "general", featured: false,
    publishedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
  },
  {
    title: "SEASON TICKETS 2025/26: ON SALE NOW",
    slug: "season-tickets-2025-26-on-sale",
    category: "ticket-news",
    summary: "Season tickets for the 2025/26 campaign are now available to purchase.",
    body: "<p>Burnley FC is pleased to announce that season tickets for the 2025/26 season are now on sale. Secure your seat at Turf Moor today.</p>",
    imageUrl: "https://images.unsplash.com/photo-1547940575-1b2b5e34f33f?w=800",
    readTime: 2, team: "general", featured: true,
    publishedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
  },
  {
    title: "COMMUNITY: CLARETS IN THE COMMUNITY SUMMER PROGRAMME",
    slug: "community-clarets-summer-programme",
    category: "community",
    summary: "Clarets in the Community launches its summer programme for young fans across Burnley.",
    body: "<p>Clarets in the Community is delighted to launch its summer programme, offering activities for young people across the borough.</p>",
    imageUrl: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=800",
    readTime: 2, team: "general", featured: false,
    publishedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
  },
];

module.exports = articles;
