const players = [
  // ── GOALKEEPERS ────────────────────────────────────────────────
  {
    name: 'James Trafford', slug: 'james-trafford',
    position: 'goalkeeper', squad: 'men', shirtNumber: 1,
    nationality: 'England', height: '6\'3"',
    photoUrl: 'https://images.unsplash.com/photo-1624526267942-ab0ff8a3e972?w=400&h=533&fit=crop&crop=face',
    bio: 'James Trafford is a highly rated England international goalkeeper who joined Burnley from Manchester City. Known for his commanding presence and shot-stopping ability.',
    stats: { appearances: 38, goals: 0, assists: 0, cleanSheets: 12, yellowCards: 1, redCards: 0 },
  },
  {
    name: 'Václav Hladký', slug: 'vaclav-hladky',
    position: 'goalkeeper', squad: 'men', shirtNumber: 13,
    nationality: 'Czech Republic', height: '6\'2"',
    photoUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&h=533&fit=crop&crop=face',
    bio: 'Experienced Czech goalkeeper providing competition and cover for the number one shirt at Turf Moor.',
    stats: { appearances: 10, goals: 0, assists: 0, cleanSheets: 3, yellowCards: 0, redCards: 0 },
  },

  // ── DEFENDERS ──────────────────────────────────────────────────
  {
    name: 'Connor Roberts', slug: 'connor-roberts',
    position: 'defender', squad: 'men', shirtNumber: 2,
    nationality: 'Wales', height: '5\'10"',
    photoUrl: 'https://images.unsplash.com/photo-1564564321837-a57b7070ac4f?w=400&h=533&fit=crop&crop=face',
    bio: 'Welsh international right-back known for his energy and athleticism. Connor Roberts is a key part of the Burnley backline.',
    stats: { appearances: 34, goals: 1, assists: 5, cleanSheets: 0, yellowCards: 4, redCards: 0 },
  },
  {
    name: 'Bashir Humphreys', slug: 'bashir-humphreys',
    position: 'defender', squad: 'men', shirtNumber: 3,
    nationality: 'England', height: '6\'0"',
    photoUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&h=533&fit=crop&crop=face',
    bio: 'Young left-back on loan who has impressed with his composure and defensive solidity.',
    stats: { appearances: 24, goals: 0, assists: 2, cleanSheets: 0, yellowCards: 2, redCards: 0 },
    onLoan: true,
  },
  {
    name: 'Jordan Beyer', slug: 'jordan-beyer',
    position: 'defender', squad: 'men', shirtNumber: 5,
    nationality: 'Germany', height: '6\'1"',
    photoUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=533&fit=crop&crop=face',
    bio: 'German centre-back who brings technical quality and calmness in possession.',
    stats: { appearances: 28, goals: 0, assists: 1, cleanSheets: 0, yellowCards: 3, redCards: 0 },
  },
  {
    name: 'Maxime Estève', slug: 'maxime-esteve',
    position: 'defender', squad: 'men', shirtNumber: 6,
    nationality: 'France', height: '6\'2"',
    photoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=533&fit=crop&crop=face',
    bio: 'French centre-back who joined from Montpellier. Commanding in the air and strong in the tackle.',
    stats: { appearances: 32, goals: 2, assists: 0, cleanSheets: 0, yellowCards: 5, redCards: 1 },
  },
  {
    name: 'Lucas Pires', slug: 'lucas-pires',
    position: 'defender', squad: 'men', shirtNumber: 33,
    nationality: 'Brazil', height: '5\'11"',
    photoUrl: 'https://images.unsplash.com/photo-1544723795-3fb6469f5b39?w=400&h=533&fit=crop&crop=face',
    bio: 'Brazilian left-back known for his attacking instincts and technical quality on the ball.',
    stats: { appearances: 20, goals: 0, assists: 3, cleanSheets: 0, yellowCards: 2, redCards: 0 },
  },
  {
    name: 'Dara Costelloe', slug: 'dara-costelloe',
    position: 'defender', squad: 'men', shirtNumber: 35,
    nationality: 'Republic of Ireland', height: '5\'9"',
    photoUrl: 'https://images.unsplash.com/photo-1463453091185-61582044d556?w=400&h=533&fit=crop&crop=face',
    bio: 'Irish defender who has come through the Burnley academy system and earned his first-team opportunities.',
    stats: { appearances: 10, goals: 0, assists: 1, cleanSheets: 0, yellowCards: 1, redCards: 0 },
  },

  // ── MIDFIELDERS ────────────────────────────────────────────────
  {
    name: 'Josh Cullen', slug: 'josh-cullen',
    position: 'midfielder', squad: 'men', shirtNumber: 4,
    nationality: 'Republic of Ireland', height: '5\'10"',
    photoUrl: 'https://images.unsplash.com/photo-1547425260-76bcadfb4f2c?w=400&h=533&fit=crop&crop=face',
    bio: 'Republic of Ireland international midfielder. A combative and technically proficient player who acts as the engine room in Parker\'s midfield.',
    stats: { appearances: 38, goals: 1, assists: 4, cleanSheets: 0, yellowCards: 7, redCards: 0 },
  },
  {
    name: 'James Ward-Prowse', slug: 'james-ward-prowse',
    position: 'midfielder', squad: 'men', shirtNumber: 7,
    nationality: 'England', height: '5\'11"',
    photoUrl: 'https://images.unsplash.com/photo-1552058544-f2b08422138a?w=400&h=533&fit=crop&crop=face',
    bio: 'Creative midfielder and set-piece specialist. James Ward-Prowse joined on loan and has been instrumental in Burnley\'s attacking play.',
    stats: { appearances: 22, goals: 6, assists: 9, cleanSheets: 0, yellowCards: 3, redCards: 0 },
    onLoan: true,
  },
  {
    name: 'Hannibal Mejbri', slug: 'hannibal',
    position: 'midfielder', squad: 'men', shirtNumber: 8,
    nationality: 'Tunisia', height: '5\'11"',
    photoUrl: 'https://images.unsplash.com/photo-1531427186611-ecfd6d936c79?w=400&h=533&fit=crop&crop=face',
    bio: 'Talented Tunisian midfielder on loan from Manchester United. Energetic box-to-box player with an eye for goal.',
    stats: { appearances: 30, goals: 4, assists: 5, cleanSheets: 0, yellowCards: 6, redCards: 0 },
    onLoan: true,
  },
  {
    name: 'Zian Flemming', slug: 'zian-flemming',
    position: 'midfielder', squad: 'men', shirtNumber: 10,
    nationality: 'Netherlands', height: '6\'0"',
    photoUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400&h=533&fit=crop&crop=face',
    bio: 'Dutch attacking midfielder who possesses excellent technical ability and contributes regularly with goals and assists.',
    stats: { appearances: 28, goals: 9, assists: 5, cleanSheets: 0, yellowCards: 4, redCards: 0 },
  },
  {
    name: 'Lesley Ugochukwu', slug: 'lesley-ugochukwu',
    position: 'midfielder', squad: 'men', shirtNumber: 16,
    nationality: 'France', height: '6\'0"',
    photoUrl: 'https://images.unsplash.com/photo-1566492031773-4f4e44671857?w=400&h=533&fit=crop&crop=face',
    bio: 'French midfielder on loan from Chelsea who brings physicality and composure to the midfield.',
    stats: { appearances: 16, goals: 0, assists: 2, cleanSheets: 0, yellowCards: 2, redCards: 0 },
    onLoan: true,
  },

  // ── FORWARDS ───────────────────────────────────────────────────
  {
    name: 'Lyle Foster', slug: 'lyle-foster',
    position: 'forward', squad: 'men', shirtNumber: 9,
    nationality: 'South Africa', height: '6\'1"',
    photoUrl: 'https://images.unsplash.com/photo-1463453091185-61582044d556?w=400&h=533&fit=crop&crop=face',
    bio: 'South African international striker who is one of Burnley\'s most potent attacking threats. Lyle Foster combines pace, power, and a clinical eye for goal.',
    stats: { appearances: 32, goals: 14, assists: 4, cleanSheets: 0, yellowCards: 2, redCards: 0 },
  },
  {
    name: 'Zeki Amdouni', slug: 'zeki-amdouni',
    position: 'forward', squad: 'men', shirtNumber: 11,
    nationality: 'Switzerland', height: '6\'0"',
    photoUrl: 'https://images.unsplash.com/photo-1459499362902-55a20553e082?w=400&h=533&fit=crop&crop=face',
    bio: 'Swiss international forward with explosive pace and a sharp finishing instinct. Has been one of the standout players in the Championship this season.',
    stats: { appearances: 30, goals: 12, assists: 3, cleanSheets: 0, yellowCards: 3, redCards: 0 },
  },
  {
    name: 'Jaidon Anthony', slug: 'jaidon-anthony',
    position: 'forward', squad: 'men', shirtNumber: 17,
    nationality: 'England', height: '5\'10"',
    photoUrl: 'https://images.unsplash.com/photo-1617979420888-3ee7b5c91ef0?w=400&h=533&fit=crop&crop=face',
    bio: 'Pacey winger who terrorises opposition defences with his directness and trickery. A key creative outlet for the Clarets.',
    stats: { appearances: 26, goals: 5, assists: 7, cleanSheets: 0, yellowCards: 1, redCards: 0 },
  },
  {
    name: 'Marcus Edwards', slug: 'marcus-edwards',
    position: 'forward', squad: 'men', shirtNumber: 19,
    nationality: 'England', height: '5\'6"',
    photoUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=400&h=533&fit=crop&crop=face',
    bio: 'Technical wide forward who joined from Sporting CP. Blessed with exceptional close control and the ability to beat defenders at will.',
    stats: { appearances: 22, goals: 3, assists: 6, cleanSheets: 0, yellowCards: 2, redCards: 0 },
  },
  {
    name: 'Luca Koleosho', slug: 'luca-koleosho',
    position: 'forward', squad: 'men', shirtNumber: 23,
    nationality: 'Spain', height: '5\'10"',
    photoUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&h=533&fit=crop&crop=face',
    bio: 'Young Spanish-American winger with electrifying pace and direct running. A real threat from the wide areas.',
    stats: { appearances: 18, goals: 2, assists: 4, cleanSheets: 0, yellowCards: 1, redCards: 0 },
  },

  // ── COACHING STAFF ─────────────────────────────────────────────
  {
    name: 'Scott Parker', slug: 'scott-parker',
    position: 'coaching-staff', squad: 'men', shirtNumber: null,
    nationality: 'England',
    photoUrl: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=400&h=533&fit=crop&crop=face',
    bio: 'Scott Parker was appointed Head Manager of Burnley FC. The former England international midfielder brings significant Championship experience and a clear tactical identity to Turf Moor.',
    stats: { appearances: 0, goals: 0, assists: 0, cleanSheets: 0, yellowCards: 0, redCards: 0 },
  },
  {
    name: 'Craig Bellamy', slug: 'craig-bellamy',
    position: 'coaching-staff', squad: 'men', shirtNumber: null,
    nationality: 'Wales',
    photoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=533&fit=crop&crop=face',
    bio: 'Former Welsh international who serves as First Team Coach, bringing extensive playing experience at the highest level.',
    stats: { appearances: 0, goals: 0, assists: 0, cleanSheets: 0, yellowCards: 0, redCards: 0 },
  },
];

module.exports = players;
